album/album/urls.py
from django.contrib import admin
from django.urls import path, include
from photo.views import home
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # 下面在配置路径
    path('photo/', include('photo.urls', namespace='photo')),
    path('', home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

album/photo/urls.py
from django.urls import path
from photo.views import (
        home,
        upload,
        oss_home,
        fetch_photos,
    )
from django.views.generic import TemplateView
from photo.views import home, upload, oss_home
# App名称
# 用于Django幕后的url查询
app_name = 'photo'
# url列表
urlpatterns = [
    path('', home, name='home'),
    path('upload/', upload, name='upload'),
    path(
        'endless-home/',
        TemplateView.as_view(template_name='photo/endless_list.html'),
        name='endless_home'
    ),
    path('fetch/', fetch_photos, name='fetch'),
    path('oss-home/', oss_home, name='oss_home'),
]

album/photo/models.py
from django.db import models
from django.utils.timezone import now
# Create your models here.
class Photo(models.Model):
    image   = models.ImageField(upload_to='photo/%Y%m%d/')
    created = models.DateTimeField(default=now)

    def __str__(self):
        return self.image.name
    class Meta:
        ordering = ('-created',)

album/photo/views.py
from django.shortcuts import render
from photo.models import Photo
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import JsonResponse
# Create your views here.
import oss2
# 填入阿里云账号的 <AccessKey ID> 和 <AccessKey Secret>
auth   = oss2.Auth('LTAI5tKtSpjepVQqtdKL19oX', 'bIREvrczbvpKWJlcZplEn02lQWT4PF')
# 填入 OSS 的 <域名> 和 <Bucket名>
bucket = oss2.Bucket(auth, 'http://oss-cn-beijing.aliyuncs.com', 'lisese-test')
def home(request):
    photos  = Photo.objects.all()
    # 新增分页代码
    paginator    = Paginator(photos, 5)
    page_number  = request.GET.get('page')
    paged_photos = paginator.get_page(page_number)
    # 将分页器对象传入上下文
    context = {'photos': paged_photos}
    # 处理登入登出的POST请求
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user     = authenticate(request, username=username, password=password)
        # 登入
        if user is not None and user.is_superuser:
            login(request, user)
        # 登出
        isLogout  = request.POST.get('isLogout')
        if isLogout == 'True':
            logout(request)
    return render(request, 'photo/list.html', context)
def upload(request):
    if request.method == 'POST' and request.user.is_superuser:
        images = request.FILES.getlist('images')
        for i in images:
            photo = Photo(image=i)
            photo.save()
    return redirect('home')
    
# 获取数据的视图
def fetch_photos(request):
    photos       = Photo.objects.values()
    paginator    = Paginator(photos, 4)
    page_number  = int(request.GET.get('page'))
    data         = {}

    # 页码正确才返回数据
    if page_number <= paginator.num_pages:
        paged_photos = paginator.get_page(page_number)
        data.update({'photos': list(paged_photos)})

    return JsonResponse(data)
class ObjIterator(oss2.ObjectIteratorV2):
    # 初始化时立即抓取图片数据
    def __init__(self, bucket):
        super().__init__(bucket)
        self.fetch_with_retry()

    # 分页要求实现__len__
    def __len__(self):
        return len(self.entries)

    # 分页要求实现__getitem__
    def __getitem__(self, key):
        return self.entries[key]

    # 此方法从云端抓取文件数据
    # 然后将数据赋值给 self.entries
    def _fetch(self):
        result = self.bucket.list_objects_v2(prefix=self.prefix,
                                          delimiter=self.delimiter,
                                          continuation_token=self.next_marker,
                                          start_after=self.start_after,
                                          fetch_owner=self.fetch_owner,
                                          encoding_type=self.encoding_type,
                                          max_keys=self.max_keys,
                                          headers=self.headers)
        self.entries = result.object_list + [oss2.models.SimplifiedObjectInfo(prefix, None, None, None, None, None)
                                             for prefix in result.prefix_list]
        # 让图片以上传时间倒序
        self.entries.sort(key=lambda obj: -obj.last_modified)

        return result.is_truncated, result.next_continuation_token
def oss_home(request):
    photos       = ObjIterator(bucket)
    paginator    = Paginator(photos, 6)
    page_number  = request.GET.get('page')
    paged_photos = paginator.get_page(page_number)
    context      = {'photos': paged_photos}

    # 省略登入登出的POST请求代码
    # ...

    return render(request, 'photo/oss_list.html', context)

album/templates/base.html
<html>
  <head>
    <meta charset="utf-8">
    <!-- 预留页面标题位置 -->
    <title>{% block title %}{% endblock title %}</title>
    <!-- bootstrap.css -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'hover.css' %}">
  </head>
  <body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js -->
    <script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
    <script 
    src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" 
    integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D"
    crossorigin="anonymous" 
    async></script>
    <!-- 预留脚本的位置 -->
    {% block scripts %}{% endblock scripts %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- 只有 bounds.js 是本地引用的 -->
    <script src="{% static 'bounds.js' %}"></script>
    <style>
        body {
            background-color:#212529;
        }
    </style>
  </body>
</html>

album/templates/footer.html
<!-- Footer -->
<div><br><br><br></div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">
            Copyright &copy; www.dusaiphoto.com 2021
        </p>
    </div>
</footer>

album/templates/header.html
<!-- 导航栏 -->
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
        <!-- 标志 -->
        <a 
            class="navbar-brand" 
            href="#"
            data-bs-toggle="modal" 
            data-bs-target="#login"
        >
            <h2>
                Awesome Album
            </h2>
        </a>
        <!-- 登录模态窗 -->
        {% if user.is_superuser %}
            <ul class="navbar-nav">
                <li class="nav-item">
                <h2>
                    <a 
                    class="nav-link active"
                    href="#"
                    data-bs-toggle="modal"
                    data-bs-target="#upload"
                    >
                        +
                    </a>
                </h2>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>
<!-- 登出 -->
{% if user.is_superuser %}
<div class="modal fade" id="login">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>确认退出账号吗？</p>
                <form action="{% url 'home' %}" method="post">{% csrf_token %}
                    <input type="text" id="isLogout" name="isLogout" value="True" hidden>
                    <button type="submit" class="btn btn-danger">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- 新增上传模态窗 -->
<div class="modal fade" id="upload">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <h5 class="modal-title">上传图片</h5>
                <form action="{% url 'photo:upload' %}"
                method="post"
                enctype="multipart/form-data"
                >
                    {% csrf_token %}
                    <div class="col py-2">
                        <input
                            class="form-control" 
                            type="file"
                            id="images" 
                            name="images" 
                            multiple="multiple"
                            accept="image/*"
                        >
                    </div>
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- 登录 -->
{% else %}
<div class="modal fade" id="login">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form action="{% url 'home' %}" method="post">{% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="pwd" class="form-label">Password</label>
                        <input type="password" class="form-control" id="pwd" name="password">
                        <div id="passwordHelp" class="form-text">
                            We'll never share your password with anyone else.
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

album/templates/photo/endless_list.html
{% extends "base.html" %}
{% block title %}首页{% endblock title %}

{% block content %}
<div class="container py-2" id="app">
    <div class="row" id="cards">
        <div v-for="photo in photos" class="col-6 py-2 grid-item">
            <div class="card hvr-float-shadow">
                <a 
                href="#"
                data-bs-toggle="modal" 
                :data-bs-target="'#photo-' + photo.id"
                >
                    <img 
                    v-if="photo !== 0"
                    :src="'/media/' + photo.image" 
                    alt=""
                    class="card-img"
                    >
                </a>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div v-for="photo in photos" class="modal fade" :id="'photo-' + photo.id">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <img 
                    :src="'/media/' + photo.image" 
                    alt=""
                    class="card-img"
                    >
                </div>
            </div>
        </div>
    </div>
</div>

<div class="box"></div>

{% endblock content %}

{% block scripts %}
<script type='text/javascript'>
    // 休眠函数用于测试
    let sleep = (time) => {
        return new Promise((resolve) => setTimeout(resolve, time));
    }

    // 监听滚动到底部的事件
    let setBounds = () => {
        const box = document.querySelector('.box');
        // 进入底部后将 Vue 的页码状态 +1
        const onEnter = () => {
            app._instance.data.pageNum += 1;
            console.log('onEnter');
        };
        // 离开底部事件
        const onLeave = () => {
            console.log('onLeave');
        };
        const boundary = bound({
            margins: {bottom: 10}
        })
        boundary.watch(box, onEnter, onLeave);
    }

    // Vue 实例
    const app = Vue.createApp({
        el: '#app',
        // 替换Vue的模板标签
        // 防止与Django冲突
        delimiters: ['[[', ']]'],
        data() {
            return {
                // 图片列表数据
                photos: [],
                // 当前页码
                pageNum: 1,
            }
        },
        // Vue实例创建完毕后，立即获取第一页的数据
        created() {
            axios.get('/photo/fetch', {
                params: {
                    page: this.pageNum
                }
            })
                .then((response) => {
                this.photos = response.data.photos;
            })
        },
        watch: {
            // 监听页码变化的事件
            // 请求下一页的数据
            pageNum(newValue, oldValue) {
                if (newValue > 1) {
                    axios
                        .get('/photo/fetch', {
                            params: {
                                page: this.pageNum
                            }
                        })
                        .then((response) => {
                            sleep(500).then(() => {
                                if (Object.keys(response.data).length !== 0) {
                                    this.photos = [...this.photos, ...response.data.photos];
                                }
                            })
                        })
                }
            }
        },
    });

    // 挂载 Vue 实例
    app.mount('#app');

    // 页面初始化完毕后，开始监听滚动事件
    $(window).on('load', function() {
        setBounds();
    })

</script>
{% endblock scripts %}

album/templates/photo/list.html
{% extends "base.html" %}
{% block title %}首页{% endblock title %}

{% block content %}
    <div class="container py-2">
        <div class="row" data-masonry='{"percentPosition": true}'>
            {% for photo in photos %}
            <div class="col-4 py-2 hvr-float-shadow">
                <a 
           href="#"
           data-bs-toggle="modal" 
           data-bs-target="#photo-{{ photo.id }}"
           >
            <img 
                 src="{{ photo.image.url }}" 
                 alt=""
                 class="card-img"
                 >
            </a>
            </div>
            {% endfor %}
        </div>
        <!-- 新增代码 -->
        <div class="row justify-content-center py-5">
            <span class="step-links paginator">
                {% if photos.has_previous %}
                    <a 
                    href="?page=1" 
                    class="paginator prevnext" >
                        &laquo;
                    </a>
                    <a 
                    href="?page={{ photos.previous_page_number }}" 
                    class="paginator prevnext">
                        {{ photos.previous_page_number }}
                    </a>
                {% endif %}

                    <span class="current">
                        {{ photos.number }}
                    </span>

                {% if photos.has_next %}
                    <a 
                    href="?page={{ photos.next_page_number }}" 
                    class="paginator prevnext">
                        {{ photos.next_page_number }}
                    </a>
                    <a 
                    href="?page={{ photos.paginator.num_pages }}"
                    class="paginator prevnext">
                        &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
    {% for photo in photos  %}
<!-- Modal -->
<div class="modal fade" id="photo-{{ photo.id }}">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <img 
                     src="{{ photo.image.url }}" 
                     alt=""
                     class="card-img"
                     >
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}
<!-- 新增代码 -->
{% block scripts %}
<style>
    .paginator {
        color: white;
        text-align: center;
        text-decoration: none;
    }
    .prevnext {
        font-size: x-large;
    }
    .current {
        font-size: xx-large;
        padding-left: 10px;
        padding-right: 10px;
    }
</style>
<script type='text/javascript'>
    $(window).on('load', function() {
        $('#cards').masonry({
        // options
        itemSelector: '.grid-item'
        });
    })
</script>
{% endblock scripts %}

album/templates/photo/oss_list.html
{% extends "base.html" %}
{% block title %}首页{% endblock title %}

{% block content %}
    <div class="container py-2">
        <div class="row" data-masonry='{"percentPosition": true}'>
            {% for photo in photos %}
            <div class="col-4 py-2 hvr-float-shadow grid-item">
                <a 
           href="#"
           data-bs-toggle="modal" 
           data-bs-target="#photo-{{ photo.id }}"
           >
            <img 
                src="https://dusai-test.oss-cn-beijing.aliyuncs.com/{{ photo.key }}"
                 alt=""
                 class="card-img"
                 >
            </a>
            </div>
            {% endfor %}
        </div>
        <!-- 新增代码 -->
        <div class="row justify-content-center py-5">
            <span class="step-links paginator">
                {% if photos.has_previous %}
                    <a 
                    href="?page=1" 
                    class="paginator prevnext" >
                        &laquo;
                    </a>
                    <a 
                    href="?page={{ photos.previous_page_number }}" 
                    class="paginator prevnext">
                        {{ photos.previous_page_number }}
                    </a>
                {% endif %}

                    <span class="current">
                        {{ photos.number }}
                    </span>

                {% if photos.has_next %}
                    <a 
                    href="?page={{ photos.next_page_number }}" 
                    class="paginator prevnext">
                        {{ photos.next_page_number }}
                    </a>
                    <a 
                    href="?page={{ photos.paginator.num_pages }}"
                    class="paginator prevnext">
                        &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
    {% for photo in photos  %}
<!-- Modal -->
<div class="modal fade" id="photo-{{ photo.id }}">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <img 
                    src="https://dusai-test.oss-cn-beijing.aliyuncs.com/{{ photo.key }}" 
                     alt=""
                     class="card-img"
                     >
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}
<!-- 新增代码 -->
{% block scripts %}
<style>
    .paginator {
        color: white;
        text-align: center;
        text-decoration: none;
    }
    .prevnext {
        font-size: x-large;
    }
    .current {
        font-size: xx-large;
        padding-left: 10px;
        padding-right: 10px;
    }
</style>
<script type='text/javascript'>
    $(window).on('load', function() {
        $('#cards').masonry({
        // options
        itemSelector: '.grid-item'
        });
    })
</script>
{% endblock scripts %}